/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on May 22, 2017, 9:06:36 AM
 */
package bissmillah;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import groovy.model.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Zidan
 */
public class Login extends javax.swing.JFrame {
     public DefaultTableModel tabModel;
    Connection conn;   
    
    String host="localhost";
        String db="prese";  // perpus_NimAnda
        String user="root";
        String pass=""; 

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUs = new javax.swing.JTextField();
        txtPa = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtUs.setFont(new java.awt.Font("Serif", 0, 14));
        getContentPane().add(txtUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, -1));

        txtPa.setFont(new java.awt.Font("Serif", 0, 14));
        txtPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, -1));

        jButton1.setFont(new java.awt.Font("Serif", 0, 18));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close r.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 30, 30));

        jPanel1.setBackground(new java.awt.Color(-12566464,true));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18));
        jLabel4.setForeground(new java.awt.Color(-1,true));
        jLabel4.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(171, 171, 171))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/User.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(-4144960,true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 160));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-211)/2, 400, 211);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
     String sql;
        String username=txtUs.getText();
        String password=txtPa.getText();
        
        try {      
       Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
        sql ="Select * from user WHERE User ='" +txtUs.getText() + "'";
        PreparedStatement st = (PreparedStatement) conn.prepareStatement(sql);
        ResultSet rs =st.executeQuery();      
        if (rs.next()) {
            if(txtUs.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi Username");
        }
        
            else if(txtPa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Isi password");
            }    
            else if(txtPa.getText().isEmpty()|| txtUs.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "IsiUsername & Password");
            } 
            else{
            
             String passs = rs.getString("Password");
             String Bagian = rs.getString("Bagian");
             if (password.equals(passs)){
                 JOptionPane.showMessageDialog(this, "Sucess");
                 if(Bagian.equals("Pemilik")){
                  Master1 tampil = new Master1();
                  tampil.setVisible(true);
                 }
                 else
                 {
                   Master tampil = new Master();
                  tampil.setVisible(true);
                 }
             }
             else
                  JOptionPane.showMessageDialog(this, "Failed !!!!");
            }
        } else
          JOptionPane.showMessageDialog(this, "Failed !!!!");
      }
      catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
      }
     dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void txtPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaActionPerformed
// TODO add your handling code here:
     String sql;
        String username=txtUs.getText();
        String password=txtPa.getText();
        
        try {      
       Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
        sql ="Select * from user WHERE User ='" +txtUs.getText() + "'";
        PreparedStatement st = (PreparedStatement) conn.prepareStatement(sql);
        ResultSet rs =st.executeQuery();      
        if (rs.next()) {
            if(txtUs.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi Username");
        }
        
            else if(txtPa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Isi password");
            }    
            else if(txtPa.getText().isEmpty()|| txtUs.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "IsiUsername & Password");
            } 
            else{
            
             String passs = rs.getString("Password");
             String Bagian = rs.getString("Bagian");
             if (password.equals(passs)){
                 JOptionPane.showMessageDialog(this, "Sucess");
                 if(Bagian.equals("Pemilik")){
                  Master1 tampil = new Master1();
                  tampil.setVisible(true);
                 }
                 else
                 {
                   Master tampil = new Master();
                  tampil.setVisible(true);
                 }
             }
             else
                  JOptionPane.showMessageDialog(this, "Failed !!!!");
            }
        } else
          JOptionPane.showMessageDialog(this, "Failed !!!!");
      }
      catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
      }
     
     
}//GEN-LAST:event_txtPaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPa;
    private javax.swing.JTextField txtUs;
    // End of variables declaration//GEN-END:variables
}
