/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anggota.java
 *
 * Created on Feb 2, 2017, 8:35:08 AM
 */
package Perpus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Anggota extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;    // import java.sql.connection

    /** Creates new form Anggota */
    public Anggota() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNoAnggota = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAnggota = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TxtCari = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        Cari = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel1.setText("No Anggota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        TxtNoAnggota.setEnabled(false);
        getContentPane().add(TxtNoAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 30));

        TxtNama.setEnabled(false);
        getContentPane().add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 270, 30));

        TxtAlamat.setEnabled(false);
        getContentPane().add(TxtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 270, 30));

        BTambah.setFont(new java.awt.Font("SansSerif", 1, 14));
        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add OK.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        BSimpan.setFont(new java.awt.Font("SansSerif", 1, 14));
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Simpan.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 40));

        BEdit.setFont(new java.awt.Font("SansSerif", 1, 14));
        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Edit OK.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 130, 40));

        BBatal.setFont(new java.awt.Font("SansSerif", 1, 14));
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Batal OK.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        getContentPane().add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 130, 40));

        BHapus.setFont(new java.awt.Font("SansSerif", 1, 14));
        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete OK.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 130, 40));

        BClose.setFont(new java.awt.Font("SansSerif", 1, 14));
        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close copy.png"))); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });
        getContentPane().add(BClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 130, 40));

        TAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 840, 110));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel4.setText("Cari Berdasarkan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        TxtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 210, 30));

        BCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search ok.png"))); // NOI18N
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 60, 40));

        Cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Anggota", "Nama Anggota" }));
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, 30));

        jPanel1.setBackground(new java.awt.Color(-4144960,true));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 48));
        jLabel5.setText("Form Anggota");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 870, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
// TODO add your handling code here:
        if(BSimpan.getText().equalsIgnoreCase("Simpan"))
            simpanData();
        else
            rubahData();
        
        TxtNoAnggota.setText(""); // txtNoAnggota Tidak Aktif
        TxtNama.setText("");        
        TxtAlamat.setText("");


        TxtNoAnggota.setEnabled(true);
        TxtNama.setEnabled(true);
        TxtAlamat.setEnabled(true);

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);       

       

}//GEN-LAST:event_BSimpanActionPerformed

private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
// TODO add your handling code here:        
        TxtNoAnggota.setEnabled(true);
        TxtNama.setEnabled(true);
        TxtAlamat.setEnabled(true);
        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(true);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BClose.setEnabled(false);

}//GEN-LAST:event_BTambahActionPerformed

private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_BCloseActionPerformed

private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
// TODO add your handling code here:
        TxtNoAnggota.setEnabled(false); // txtNoAnggota Tidak Aktif
        TxtNama.setEnabled(true);       // txtNama          Aktif
        TxtAlamat.setEnabled(true);     // txtAlamat Aktif

        BSimpan.setText("Update"); // Merubah Teks Tombol Simpan

        // Memanggil Method  ambilData_dari_JTable()
        ambilData_dari_JTable();

}//GEN-LAST:event_BEditActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
                    hapus_Data();
    }//GEN-LAST:event_BHapusActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        // TODO add your handling code here:
            String sql;
        int pilih = Cari.getSelectedIndex();
        String cari = TxtCari.getText();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        if(pilih==0)
        sql ="Select * from Tb_Anggota WHERE No_Anggota ='" +TxtCari.getText() + "'";
        else
        sql ="Select * from Tb_Anggota WHERE Nama_Anggota Like '%" +TxtCari.getText() + "%'";

        PreparedStatement st = conn.prepareStatement(sql);
        ResultSet rs =st.executeQuery();

        hapusIsiJTable();
        int no=0;
        while (rs.next()) {
            no++;
             String NoAnggota = rs.getString("No_Anggota");
             String Nama = rs.getString("Nama_Anggota");
             String Alamat = rs.getString("Alamat");
             Object [] data = {no,NoAnggota, Nama, Alamat};
             tabModel.addRow(data);
        }

         if(tabModel.getRowCount()>0)         
           JOptionPane.showMessageDialog(this,"Data Ditemukan ");        
        else
            JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

      }
      catch (ClassNotFoundException se) {}  // Silahkan tambahkan sendiri informasi eksepsi
      catch (SQLException se) {} 

    }//GEN-LAST:event_BCariActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        TxtNoAnggota.setText(""); // txtNoAnggota Tidak Aktif
        TxtNama.setText("");        // txtNama          Aktif
        TxtAlamat.setText("");

       // Mengatur  Enable Tombol Dan Textfield  
        TxtNoAnggota.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtAlamat.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);

    }//GEN-LAST:event_BBatalActionPerformed

private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CariActionPerformed

private void TxtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Anggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCari;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> Cari;
    private javax.swing.JTable TAnggota;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNoAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getData(){
  
  try{
        //Memanggil Driver
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        //Membuat variabel bertipe Connection
        //Kelas Connection berfungsi menyimpan sebuah koneksi yang sudah dilakukan oleh DriverManger
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   // import java.sql.DriverManager
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        String sql="Select * from Tb_Anggota";
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String NoAnggota,Nama,Alamat;
        int no=0;
        while(rs.next()){
         no=no+1;
         NoAnggota=rs.getString("No_Anggota");
         Nama=rs.getString("Nama_Anggota");
         Alamat=rs.getString("Alamat");

         Object Data[]={no,NoAnggota,Nama,Alamat};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }// Akhir Method getData

private void setJTable(){
    String [] JudulKolom={"No","No Anggota","Nama Anggota","Alamat"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TAnggota.setModel(tabModel);
    TAnggota.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TAnggota.getColumnModel().getColumn(0).setPreferredWidth(30);
    TAnggota.getColumnModel().getColumn(1).setPreferredWidth(100);
    TAnggota.getColumnModel().getColumn(2).setPreferredWidth(160);
    TAnggota.getColumnModel().getColumn(3).setPreferredWidth(300);

    getData();

}// Akhir Method setJTable

    void ambilData_dari_JTable() {
    int row = TAnggota.getSelectedRow();

    // Mengambil data yang dipilih pada JTable
    String NoAnggota = tabModel.getValueAt(row, 1).toString();
    String Nama = tabModel.getValueAt(row, 2).toString();
    String Alamat = tabModel.getValueAt(row, 3).toString();
    
    TxtNoAnggota.setText(NoAnggota);
    TxtNama.setText(Nama);
    TxtAlamat.setText(Alamat);
  }
    
    // Method Untuk Menghapus Semua Isi JTable
public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }
//  Method Untuk Menampilkan Data dari tabel Anggota Ke JTable
public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   
        String sql="Select * from Tb_Anggota";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String NoAnggota,Nama,Alamat;
        int no=0;
        while(rs.next()){
         no=no+1;
         NoAnggota=rs.getString("No_Anggota");
         Nama=rs.getString("Nama_Anggota");
         Alamat=rs.getString("Alamat");
         Object Data[]={no,NoAnggota,Nama,Alamat};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

    public void rubahData() {
    // Konfirmasi sebelum melakukan perubahan data
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan No Anggota = '" + TxtNoAnggota.getText() + "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);
    // Apabila tombol Yes ditekan
    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql ="UPDATE Tb_Anggota SET Nama_Anggota = ?, Alamat= ? WHERE No_Anggota = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, TxtNama.getText());
          st.setString(2, TxtAlamat.getText());
          st.setString(3, TxtNoAnggota.getText());
          st.executeUpdate();

         // Memanggil Method   tampilDataKeJTable();
          tampilDataKeJTable();

          TxtNoAnggota.setText("");
          TxtNama.setText("");
          TxtAlamat.setText("");
        } catch (SQLException se) { }     // Silahkan tambahkan Sendiri informasi Eksepsi
      } catch (ClassNotFoundException se) {} // Silahkan tambahkan Sendiri informasi Eksepsi
      catch (SQLException se) {}  // Silahkan tambahkan Sendiri informasi Eksepsi
    }
    
  }

    public void simpanData(){
//Connection conn;
     try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            String sql="Insert into Tb_Anggota values(?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, TxtNoAnggota.getText());
                st.setString(2, TxtNama.getText());
                st.setString(3, TxtAlamat.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Gagal Tuh.. Bego Lu " +e.getMessage());
        }
  }

public void hapus_Data() {
    // Konfirmasi sebelum melakukan penghapusan data
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan No Anggota = '" + TxtNoAnggota.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {     // Apabila tombol OK ditekan
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql = "DELETE FROM Tb_Anggota WHERE No_Anggota = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, TxtNoAnggota.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        TxtNoAnggota.setText("");
        TxtNama.setText("");
        TxtAlamat.setText("");
      } catch (Exception se) {  // Silahkan tambahkan catch Exception yang lain
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }


    
}
