/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anggota.java
 *
 * Created on Feb 2, 2017, 8:35:08 AM
 */
package Perpus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Buku extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;    // import java.sql.connection

    /** Creates new form Buku */
    public Buku() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtISBN = new javax.swing.JTextField();
        TxtJudul = new javax.swing.JTextField();
        TxtPengarang = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBuku = new javax.swing.JTable();
        TxtPenerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtTahun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtCari = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        Carii = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("ISBN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Judul Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Pengarang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(TxtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, 30));
        getContentPane().add(TxtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 270, 30));
        getContentPane().add(TxtPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, 30));

        BTambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add OK.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 40));

        BSimpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Simpan.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 130, 40));

        BEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Edit OK.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 130, 40));

        BBatal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Batal OK.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        getContentPane().add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 130, 40));

        BHapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete OK.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 130, 40));

        BClose.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close copy.png"))); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });
        getContentPane().add(BClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 130, 40));

        TBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 830, 110));
        getContentPane().add(TxtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 290, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Penerbit ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));
        getContentPane().add(TxtTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 290, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Tahun Terbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));
        getContentPane().add(TxtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 290, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Cari Berdasarkan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        getContentPane().add(TxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 210, 30));

        BCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search ok.png"))); // NOI18N
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 50, 40));

        Carii.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Judul" }));
        getContentPane().add(Carii, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 60, 30));

        jPanel1.setBackground(new java.awt.Color(-4144960,true));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel8.setText("Form Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel8)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
// TODO add your handling code here:
if(BSimpan.getText().equalsIgnoreCase("Simpan"))
            simpanData();
        else
            rubahData();
        
        TxtISBN.setText(""); // txtNoAnggota Tidak Aktif
        TxtJudul.setText("");        
        TxtPengarang.setText("");
        TxtPenerbit.setText("");
        TxtTahun.setText("");
        TxtStatus.setText("");
        
        TxtISBN.setEnabled(true); // txtNoAnggota Tidak Aktif
        TxtJudul.setEnabled(true);       // txtNama Aktif
        TxtPengarang.setEnabled(true);     // txtAlamat Aktif
        TxtPenerbit.setEnabled(true);       // txtNama Aktif
        TxtTahun.setEnabled(true);       // txtNama Aktif
        TxtStatus.setEnabled(true);       // txtNama Aktif

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(true);
        BBatal.setEnabled(true);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);   
}//GEN-LAST:event_BSimpanActionPerformed

private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
// TODO add your handling code here:
        TxtISBN.setEnabled(true);
        TxtJudul.setEnabled(true);
        TxtPengarang.setEnabled(true);
        TxtPenerbit.setEnabled(true);
        TxtTahun.setEnabled(true);
        TxtStatus.setEnabled(true);
        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BClose.setEnabled(false);
}//GEN-LAST:event_BTambahActionPerformed

private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_BCloseActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        TxtISBN.setEnabled(false); // txtNoAnggota Tidak Aktif
        TxtJudul.setEnabled(true);       // txtNama Aktif
        TxtPengarang.setEnabled(true);     // txtAlamat Aktif
        TxtPenerbit.setEnabled(true);       // txtNama Aktif
        TxtTahun.setEnabled(true);       // txtNama Aktif
        TxtStatus.setEnabled(true);       // txtNama Aktif

        BSimpan.setText("Update"); // Merubah Teks Tombol Simpan
        
        BTambah.setEnabled(true);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BClose.setEnabled(false);

        // Memanggil Method  ambilData_dari_JTable()
        ambilData_dari_JTable();
    }//GEN-LAST:event_BEditActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = Carii.getSelectedIndex();
        String cari = TxtCari.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            if(pilih==0)
            sql ="Select * from Tb_Buku WHERE ISBN ='" +TxtCari.getText() + "'";
            else
            sql ="Select * from Tb_Buku WHERE Judul Like '%" +TxtCari.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String ISBN = rs.getString("ISBN");
                String Judul = rs.getString("Judul");
                String Pengarang = rs.getString("Pengarang");
                Object [] data = {no,ISBN, Judul, Pengarang};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
            JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
            JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        }
        catch (ClassNotFoundException se) {}  // Silahkan tambahkan sendiri informasi eksepsi
        catch (SQLException se) {}
    }//GEN-LAST:event_BCariActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        TxtISBN.setText(""); // txtNoAnggota Tidak Aktif
        TxtJudul.setText("");        // txtNama          Aktif
        TxtPengarang.setText("");
        TxtPenerbit.setText("");
        TxtTahun.setText("");
        TxtStatus.setText("");

       // Mengatur  Enable Tombol Dan Textfield  
        TxtISBN.setEnabled(false);
        TxtJudul.setEnabled(false);
        TxtPengarang.setEnabled(false);
        TxtPenerbit.setEnabled(false);
        TxtTahun.setEnabled(false);
        TxtStatus.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);
    }//GEN-LAST:event_BBatalActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
    }//GEN-LAST:event_BHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Buku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCari;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> Carii;
    private javax.swing.JTable TBuku;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JTextField TxtISBN;
    private javax.swing.JTextField TxtJudul;
    private javax.swing.JTextField TxtPenerbit;
    private javax.swing.JTextField TxtPengarang;
    private javax.swing.JTextField TxtStatus;
    private javax.swing.JTextField TxtTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getData(){
  Connection conn;    // import java.sql.connection
  try{
        //Memanggil Driver
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        //Membuat variabel bertipe Connection
        //Kelas Connection berfungsi menyimpan sebuah koneksi yang sudah dilakukan oleh DriverManger
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   // import java.sql.DriverManager
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        String sql="Select * from Tb_Buku";
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String ISBN,Judul,Pengarang,Penerbit,TahunTerbit,Status;
        int no=0;
        while(rs.next()){
         no=no+1;
         ISBN=rs.getString("ISBN");
         Judul=rs.getString("Judul");
         Pengarang=rs.getString("Pengarang");
         Penerbit=rs.getString("Penerbit");
         TahunTerbit=rs.getString("Tahun_Terbit");
         Status=rs.getString("Status");

         Object Data[]={no,ISBN,Judul,Pengarang,Penerbit,TahunTerbit,Status};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }// Akhir Method getData

private void setJTable(){
    String [] JudulKolom={"No","ISBN","Judul","Pengarang","Penerbit","Tahun Terbit","Status"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false};
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TBuku.setModel(tabModel);
    TBuku.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TBuku.getColumnModel().getColumn(0).setPreferredWidth(30);
    TBuku.getColumnModel().getColumn(1).setPreferredWidth(100);
    TBuku.getColumnModel().getColumn(2).setPreferredWidth(160);
    TBuku.getColumnModel().getColumn(3).setPreferredWidth(300);
    TBuku.getColumnModel().getColumn(4).setPreferredWidth(250);
    TBuku.getColumnModel().getColumn(5).setPreferredWidth(100);
    TBuku.getColumnModel().getColumn(6).setPreferredWidth(100);

    getData();
}// Akhir Method setJTable

void ambilData_dari_JTable() {
    int row = TBuku.getSelectedRow();

    // Mengambil data yang dipilih pada JTable
    String ISBN = tabModel.getValueAt(row, 1).toString();
    String Judul = tabModel.getValueAt(row, 2).toString();
    String Pengarang = tabModel.getValueAt(row, 3).toString();
    String Penerbit = tabModel.getValueAt(row, 4).toString();
    String Tahun = tabModel.getValueAt(row, 5).toString();
    String Status = tabModel.getValueAt(row, 6).toString();
    
    TxtISBN.setText(ISBN);
    TxtJudul.setText(Judul);
    TxtPengarang.setText(Pengarang);
    TxtPenerbit.setText(Penerbit);
    TxtTahun.setText(Tahun);
    TxtStatus.setText(Status);
  }
    
    // Method Untuk Menghapus Semua Isi JTable
public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }
//  Method Untuk Menampilkan Data dari tabel Anggota Ke JTable
public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   
        String sql="Select * from Tb_Buku";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String ISBN,Judul,Pengarang,Penerbit,Tahun,Status;
        int no=0;
        while(rs.next()){
         no=no+1;
         ISBN=rs.getString("ISBN");
         Judul=rs.getString("Judul");
         Pengarang=rs.getString("Pengarang");
         Penerbit=rs.getString("Penerbit");
         Tahun=rs.getString("Tahun_Terbit");
         Status=rs.getString("Status");
         Object Data[]={no,ISBN,Judul,Pengarang,Penerbit,Tahun};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {
    // Konfirmasi sebelum melakukan perubahan data
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan ISBN = '" + TxtISBN.getText() + "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);
    // Apabila tombol Yes ditekan
    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql ="UPDATE Tb_Buku SET Judul = ?, Pengarang= ?, Penerbit = ?, Tahun_Terbit = ?, Status = ?  WHERE ISBN = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
                
                st.setString(1, TxtJudul.getText());
                st.setString(2, TxtPengarang.getText());
                st.setString(3, TxtPenerbit.getText());
                st.setString(4, TxtTahun.getText());
                st.setString(5, TxtStatus.getText());
                st.setString(6, TxtISBN.getText());
          st.executeUpdate();

         // Memanggil Method   tampilDataKeJTable();
          tampilDataKeJTable();

        TxtISBN.setText("");
        TxtJudul.setText("");
        TxtPengarang.setText("");
        TxtPenerbit.setText("");
        TxtTahun.setText("");
        TxtStatus.setText("");
        
        } catch (SQLException se) { }     // Silahkan tambahkan Sendiri informasi Eksepsi
      } catch (ClassNotFoundException se) {} // Silahkan tambahkan Sendiri informasi Eksepsi
      catch (SQLException se) {}  // Silahkan tambahkan Sendiri informasi Eksepsi
    }
    
  }

public void simpanData(){
//Connection conn;
     try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            String sql="Insert into Tb_Buku values(?,?,?,?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, TxtISBN.getText());
                st.setString(2, TxtJudul.getText());
                st.setString(3, TxtPengarang.getText());
                st.setString(4, TxtPenerbit.getText());
                st.setString(5, TxtTahun.getText());
                st.setString(6, TxtStatus.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Gagal Tuh.. Bego Lu " +e.getMessage());
        }
  }

public void hapus_Data() {
    // Konfirmasi sebelum melakukan penghapusan data
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan ISBN = '" + TxtISBN.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {     // Apabila tombol OK ditekan
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql = "DELETE FROM Tb_Buku WHERE ISBN = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, TxtISBN.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        TxtISBN.setText("");
        TxtJudul.setText("");
        TxtPengarang.setText("");
        TxtPenerbit.setText("");
        TxtTahun.setText("");
        TxtStatus.setText("");
      } catch (Exception se) {  // Silahkan tambahkan catch Exception yang lain
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }
    
}
