/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Perpus;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smk-ib
 */
public class Peminjaman extends javax.swing.JFrame { 
    public DefaultTableModel tabModel;
    Connection conn;

    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        setJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtTanggalPinjam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtNoPinjam = new javax.swing.JTextField();
        TxtNoAnggota = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        BClose = new javax.swing.JButton();
        BTTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPinjam = new javax.swing.JTable();
        TxtJudul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtKodeBuku = new javax.swing.JTextField();
        TxtStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("No Anggota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("No Pinjam");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(TxtTanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 190, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Tgl Pinjam");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        jPanel1.add(TxtNoPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 170, 30));

        TxtNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNoAnggotaKeyPressed(evt);
            }
        });
        jPanel1.add(TxtNoAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 30));

        TxtNama.setEnabled(false);
        jPanel1.add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 160));

        BClose.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close copy.png"))); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });
        getContentPane().add(BClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 140, 40));

        BTTambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BTTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add OK.png"))); // NOI18N
        BTTambah.setText("Tambah");
        BTTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 40));

        BSimpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Simpan.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 120, 40));

        BBatal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Batal OK.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        getContentPane().add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 120, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setBackground(new java.awt.Color(204, 204, 204));
        BTambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add OK.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        BTambah.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                BTambahAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 40));

        BHapus.setBackground(new java.awt.Color(204, 204, 204));
        BHapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete OK.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        jPanel2.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 40));

        TPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TPinjam);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 90));

        TxtJudul.setEnabled(false);
        TxtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJudulActionPerformed(evt);
            }
        });
        jPanel2.add(TxtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Judul");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Kode Buku");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TxtKodeBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodeBukuKeyPressed(evt);
            }
        });
        jPanel2.add(TxtKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 30));

        TxtStatus.setEnabled(false);
        jPanel2.add(TxtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 190, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Status");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 230));

        jPanel3.setBackground(new java.awt.Color(-8355712,true));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setText("Form Peminjaman");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel8)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJudulActionPerformed

    private void TxtNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNoAnggotaKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==10){
            try {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
                String sql="select * from Tb_Anggota Where No_Anggota=?";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,TxtNoAnggota.getText());
                ResultSet rs= st.executeQuery();
                if( rs.next()){
                    String Nama = rs.getString("Nama_Anggota");
                    TxtNama.setText(Nama);
                } else{
                    JOptionPane.showMessageDialog(this, "No Anggota Tidak  Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    TxtNama.setText("");
                }
            } // akhir try
            catch(Exception e){
                System.out.println("Koneksi Gagal " +e.getMessage());
            }
        }

    }//GEN-LAST:event_TxtNoAnggotaKeyPressed

    private void TxtKodeBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeBukuKeyPressed
        // TODO add your handling code here:]
        if (evt.getKeyCode()==10){           
      try {
      Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
      conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
      String sql="select * from Tb_Buku Where ISBN=?";
      PreparedStatement st=conn.prepareStatement(sql);
      st.setString(1,TxtKodeBuku.getText());
      ResultSet rs= st.executeQuery();

      if( rs.next()){
      String Judul = rs.getString("Judul");
      String Status = rs.getString("Status");
      TxtJudul.setText(Judul);
      TxtStatus.setText(Status);
      }else
      {
      JOptionPane.showMessageDialog(this, "Kode Buku Tidak Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
      TxtJudul.setText("");
      TxtStatus.setText("");
      }
      } // akhir try
        catch(Exception e){
           System.out.println("Exception :  " +e);
        }
    }

        
    }//GEN-LAST:event_TxtKodeBukuKeyPressed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
                try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            if(TxtNama.getText().isEmpty() || tabModel.getRowCount()==0 ){
                JOptionPane.showMessageDialog(this,"Silahkan Input Anggota dan Buku");
            } else {
                // Menyimpan ke Tabel Pinjam
                String sql="insert into Tb_Peminjaman values(?,?,?,?)";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,TxtNoPinjam.getText());
                st.setString(2,TxtNoAnggota.getText());
                st.setString(3,TxtNama.getText());
                st.setString(4,TxtKodeBuku.getText());
                int rs= st.executeUpdate();

                String ISBN = null, Judul = null,Nama; int rs2=0;
                int jum=tabModel.getRowCount();
                for(int i=0;i<jum;i++){
                    // Menyimpan Ke detail Pinjam
                    String sql2="insert into DetailPinjam2 values(?,?,?)";
                    PreparedStatement st2=conn.prepareStatement(sql2);
                    ISBN = tabModel.getValueAt(i, 0).toString();
                    st2.setString(1,TxtNoPinjam.getText());
                    st2.setString(2,ISBN);
                    st2.setString(3,"Pinjam");
                    rs2= st2.executeUpdate();


                    // Merubah status Buku
                    String sql3="update Tb_Buku set Status=? where ISBN=?";
                    PreparedStatement st3=conn.prepareStatement(sql3);
                    st3.setString(1,"Dipinjam");
                    st3.setString(2,ISBN);
                    st3.executeUpdate();
                }
                if((rs>0) && (rs2>0)){
                    JOptionPane.showMessageDialog(this,"Input Berhasil");
                    Kosongkan();
                } else
                    JOptionPane.showMessageDialog(this,"Input Gagal");
                conn.close();
            }

        } // akhir try
        catch(Exception e){
            System.out.println("Exception " +e );

        
}
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BTTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTambahActionPerformed
        // TODO add your handling code here:
         Date tgl_sekarang=new Date();
        SimpleDateFormat format=new SimpleDateFormat("dd/MM/yyyy");
        String tgl=format.format(tgl_sekarang);
        TxtTanggalPinjam.setText(tgl);

        TxtNoPinjam.setEnabled(true);
        TxtNoAnggota.setEnabled(true);
        TxtKodeBuku.setEnabled(true);

    }//GEN-LAST:event_BTTambahActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
         Kosongkan();
    }//GEN-LAST:event_BBatalActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BCloseActionPerformed

private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        int row=TPinjam.getSelectedRow();
        System.out.println(row);
        if(row>=0)
            tabModel.removeRow(row);
        else
            JOptionPane.showMessageDialog(this, "Hapus Gagal");
}//GEN-LAST:event_BHapusActionPerformed

private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
                String KodeBuku;
        boolean ketemu=false;

        int jum=tabModel.getRowCount();
        if(TxtStatus.getText().equalsIgnoreCase("Ada")){

            for(int i=0;i<jum;i++){
                KodeBuku = tabModel.getValueAt(i, 0).toString();
                if(KodeBuku.equalsIgnoreCase(TxtKodeBuku.getText())){
                    JOptionPane.showMessageDialog(this,"Buku Sudah Ada Pada List Pinjaman");
                    ketemu=true;
                    TPinjam.setRowSelectionInterval(i, i);
                    break;}
            }
            if (ketemu==false) {
                String Data[]={TxtKodeBuku.getText(),TxtJudul.getText()};
                tabModel.addRow(Data);

                TxtKodeBuku.setText("");
                TxtJudul.setText("");
                TxtStatus.setText("");
            }
        } else
            JOptionPane.showMessageDialog(this, "Buku ini sedang dipinjam","Informasi",JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_BTambahActionPerformed

private void BTambahAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BTambahAncestorAdded
// TODO add your handling code here:
}//GEN-LAST:event_BTambahAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTTambah;
    private javax.swing.JButton BTambah;
    private javax.swing.JTable TPinjam;
    private javax.swing.JTextField TxtJudul;
    private javax.swing.JTextField TxtKodeBuku;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNoAnggota;
    private javax.swing.JTextField TxtNoPinjam;
    private javax.swing.JTextField TxtStatus;
    private javax.swing.JTextField TxtTanggalPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setJTable(){
    String [] JudulKolom={"ISBN","Judul"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TPinjam.setModel(tabModel);
    TPinjam.getColumnModel().getColumn(0).setPreferredWidth(100);
    TPinjam.getColumnModel().getColumn(1).setPreferredWidth(200);
}
private void Kosongkan(){
     TxtNoPinjam.setText("");
     TxtNoAnggota.setText("");
     TxtTanggalPinjam.setText("");
     TxtNama.setText("");
     TxtKodeBuku.setText("");
     TxtJudul.setText("");
     TxtStatus.setText("");

     int row=tabModel.getRowCount();
     for(int i=0;i<row;i++){
         tabModel.removeRow(0);
     }

     TxtNoPinjam.setEnabled(false);
     TxtNoAnggota.setEnabled(false);
     TxtKodeBuku.setEnabled(false);

 }

}
