/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Perpus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nina
 */
public class User extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;    // import java.sql.connection

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        setJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbBagian = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CBCari = new javax.swing.JComboBox<String>();
        TxtCari = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TUser = new javax.swing.JTable();
        TxtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        CbBagian.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Sirkulasi" }));
        getContentPane().add(CbBagian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel4.setText("Bagian");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel7.setText("Cari Berdasarkan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        CBCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Username", "Bagian" }));
        CBCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCariActionPerformed(evt);
            }
        });
        getContentPane().add(CBCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 90, 30));
        getContentPane().add(TxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 180, 30));

        BCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search ok.png"))); // NOI18N
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 50, -1));

        BTambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add OK.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 50));

        BSimpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Simpan.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, 50));

        BEdit.setFont(new java.awt.Font("SansSerif", 1, 14));
        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Edit OK.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 110, 50));

        BBatal.setFont(new java.awt.Font("SansSerif", 1, 14));
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Batal OK.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        getContentPane().add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 110, 50));

        BHapus.setFont(new java.awt.Font("SansSerif", 1, 14));
        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete OK.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, 50));

        BClose.setFont(new java.awt.Font("SansSerif", 1, 14));
        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close copy.png"))); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });
        getContentPane().add(BClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 130, -1));

        TUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 780, 110));

        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        jPanel1.setBackground(new java.awt.Color(-4144960,true));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48));
        jLabel3.setText("Form User");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void CBCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCariActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCari.getSelectedIndex();
        String cari = TxtCari.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            if(pilih==0)
            sql ="Select * from Tb_User WHERE Username ='" +TxtCari.getText() + "'";
            else
            sql ="Select * from Tb_User WHERE Bagian Like '%" +TxtCari.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String Username = rs.getString("Username");
                String Password = rs.getString("Password");
                String Bagian = rs.getString("Bagian");
                
                Object [] data = {no,Username, Password, Bagian};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
            JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
            JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        }
        catch (ClassNotFoundException se) {}  // Silahkan tambahkan sendiri informasi eksepsi
        catch (SQLException se) {}
    }//GEN-LAST:event_BCariActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        TxtUser.setEnabled(true);
        TxtPassword.setEnabled(true);
        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BClose.setEnabled(false);
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(BSimpan.getText().equalsIgnoreCase("Simpan"))
        simpanData();
        else
        rubahData();

        TxtUser.setText(""); // txtNoAnggota Tidak Aktif
        TxtPassword.setText("");
        CbBagian.setSelectedItem("");
        

        TxtUser.setEnabled(true); // txtNoAnggota Tidak Aktif
        TxtPassword.setEnabled(true);       // txtNama Aktif
        CbBagian.setEnabled(true);       // txtNama Aktif

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(true);
        BBatal.setEnabled(true);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        TxtUser.setEnabled(false); // txtNoAnggota Tidak Aktif
        TxtPassword.setEnabled(true);       // txtNama Aktif

        BSimpan.setText("Update"); // Merubah Teks Tombol Simpan

        BTambah.setEnabled(true);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BClose.setEnabled(false);

        // Memanggil Method  ambilData_dari_JTable()
        ambilData_dari_JTable();
    }//GEN-LAST:event_BEditActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        TxtUser.setText(""); // txtNoAnggota Tidak Aktif
        TxtPassword.setText("");        // txtNama          Aktif

        // Mengatur  Enable Tombol Dan Textfield
        TxtUser.setEnabled(false);
        TxtPassword.setEnabled(false);
       
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BClose.setEnabled(true);
    }//GEN-LAST:event_BBatalActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
    }//GEN-LAST:event_BHapusActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BCloseActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCari;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CBCari;
    private javax.swing.JComboBox<String> CbBagian;
    private javax.swing.JTable TUser;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getData(){
  
  try{
        //Memanggil Driver
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        //Membuat variabel bertipe Connection
        //Kelas Connection berfungsi menyimpan sebuah koneksi yang sudah dilakukan oleh DriverManger
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   // import java.sql.DriverManager
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        String sql="Select * from Tb_User";
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String Username,Password,Bagian;
        int no=0;
        while(rs.next()){
         no=no+1;
         Username=rs.getString("Username");
         Password=rs.getString("Password");
         Bagian=rs.getString("Bagian");

         Object Data[]={no,Username,Password,Bagian};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }// Akhir Method getData

private void setJTable(){
    String [] JudulKolom={"No","Username","Password","Bagian"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TUser.setModel(tabModel);
    TUser.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TUser.getColumnModel().getColumn(0).setPreferredWidth(30);
    TUser.getColumnModel().getColumn(1).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(2).setPreferredWidth(160);
    TUser.getColumnModel().getColumn(3).setPreferredWidth(300);

    getData();

}// Akhir Method setJTable

    void ambilData_dari_JTable() {
    int row = TUser.getSelectedRow();

    // Mengambil data yang dipilih pada JTable
    String Username = tabModel.getValueAt(row, 1).toString();
    String Password = tabModel.getValueAt(row, 2).toString();
    String Bagian = tabModel.getValueAt(row, 3).toString();
    
    TxtUser.setText(Username);
    TxtPassword.setText(Password);
    
  }
    
    // Method Untuk Menghapus Semua Isi JTable
public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }
//  Method Untuk Menampilkan Data dari tabel Anggota Ke JTable
public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");   
        String sql="Select * from Tb_User";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String Username,Password,Bagian;
        int no=0;
        while(rs.next()){
         no=no+1;
         Username=rs.getString("Username");
         Password=rs.getString("Password");
         Bagian=rs.getString("Bagian");
         Object Data[]={no,Username,Password,Bagian};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

    public void rubahData() {
    // Konfirmasi sebelum melakukan perubahan data
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan Username = '" + TxtUser.getText() + "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);
    // Apabila tombol Yes ditekan
    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql ="UPDATE Tb_User SET Password = ?, Bagian= ? WHERE Username = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, TxtUser.getText());
          st.setString(2, TxtPassword.getText());
          st.setObject(3, CbBagian.getSelectedItem());
          st.executeUpdate();

         // Memanggil Method   tampilDataKeJTable();
          tampilDataKeJTable();

          TxtUser.setText("");
          TxtPassword.setText("");
          CbBagian.setSelectedItem("");
        } catch (SQLException se) { }     // Silahkan tambahkan Sendiri informasi Eksepsi
      } catch (ClassNotFoundException se) {} // Silahkan tambahkan Sendiri informasi Eksepsi
      catch (SQLException se) {}  // Silahkan tambahkan Sendiri informasi Eksepsi
    }
    
  }

    public void simpanData(){
//Connection conn;
     try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
            String sql="Insert into Tb_User values(?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, TxtUser.getText());
                st.setString(2, TxtPassword.getText());
                st.setObject(3, CbBagian.getSelectedItem());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Gagal Tuh.. Bego Lu " +e.getMessage());
        }
  }

public void hapus_Data() {
    // Konfirmasi sebelum melakukan penghapusan data
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan Username = '" + TxtUser.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {     // Apabila tombol OK ditekan
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:Perpus_1514004");
        String sql = "DELETE FROM Tb_User WHERE Username = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, TxtUser.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        TxtUser.setText("");
        TxtPassword.setText("");
        CbBagian.setSelectedItem("");
      } catch (Exception se) {  // Silahkan tambahkan catch Exception yang lain
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }
}

