/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pemesanan.java
 *
 * Created on Apr 14, 2017, 11:20:41 PM
 */
package kuizkereta;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Zidan
 */
public class pemesanan extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;   
    
    String host="localhost";
        String db="kuizz";  // perpus_NimAnda
        String user="root";
        String pass=""; 

    /** Creates new form pemesanan */
    public pemesanan() {
        initComponents();
        setJTable();
        
        txtJumlah.setDocument(new JTextFieldFilter(JTextFieldFilter.numeric)); 
        nama.setDocument(new JTextFieldFilter(JTextFieldFilter.huruf));
        txtJumlah.setDocument(new JTextFieldFilter(JTextFieldFilter.numeric));
        txtHarga.setDocument(new JTextFieldFilter(JTextFieldFilter.numeric));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        cbKelas = new javax.swing.JComboBox();
        cbJurusan = new javax.swing.JComboBox();
        cbNamaKereta = new javax.swing.JComboBox();
        nama = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtPrint = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(-12566464,true));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24));
        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("Pemesanan");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 50));

        jPanel2.setBackground(new java.awt.Color(-4144960,true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel2.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 30, 30));

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, -1));

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ekonomi", "Bisnis" }));
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });
        jPanel2.add(cbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        cbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJurusanActionPerformed(evt);
            }
        });
        jPanel2.add(cbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        cbNamaKereta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ceria", "Malam", "Bersama" }));
        cbNamaKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaKeretaActionPerformed(evt);
            }
        });
        jPanel2.add(cbNamaKereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 220, -1));

        txtID.setEnabled(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel2.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, -1));

        txtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 150, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        Tambah.setText("Simpan");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        jPanel2.add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, -1));

        jLabel6.setText("Jumlah Pemesanan");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setText("Harga");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel3.setText("Jurusan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel4.setText("Kelas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel2.setText("Nama Pemesan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel7.setText("ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 20, -1));

        jLabel9.setText("Nama Kereta");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });
        jPanel2.add(bBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 110, -1));

        jPanel3.setBackground(new java.awt.Color(-12566464,true));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 380, -1));

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 310, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 360));

        jLabel8.setText("Nama Pemesan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-397)/2, (screenSize.height-416)/2, 397, 416);
    }// </editor-fold>//GEN-END:initComponents

private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtJumlahActionPerformed

private void cbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJurusanActionPerformed
// TODO add your handling code here:
     String sql;
     try{
        Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass); 
            sql="select * from destinasi where Jurusan='" + cbJurusan.getSelectedItem() + "' and Kelas='" + cbKelas.getSelectedItem() + "'" ;
            PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();
            while (rs.next()){
                txtHarga.setText("");
                    String harga = rs.getString("harga");
                    txtHarga.setText(harga);
                    
            }
     }
     catch (ClassNotFoundException se) {}
     catch (SQLException se){}
}//GEN-LAST:event_cbJurusanActionPerformed

private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtHargaActionPerformed

private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
// TODO add your handling code here:
    String sql;
     try{
        Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
            sql="select * from destinasi where Kelas='" + cbKelas.getSelectedItem() + "'";
            PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();
            
            cbJurusan.removeAllItems();
            while (rs.next()){
                String jurusan = rs.getString("Jurusan");
                cbJurusan.addItem(jurusan);
            }
     }
      catch (ClassNotFoundException se) {}
     catch (SQLException se){}
     
}//GEN-LAST:event_cbKelasActionPerformed

private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
// TODO add your handling code here:
     cetuk1();
}//GEN-LAST:event_btnPrintActionPerformed

private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtIDActionPerformed

private void cbNamaKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaKeretaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbNamaKeretaActionPerformed

private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_namaActionPerformed

private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
// TODO add your handling code here:
    try{
            Class.forName("com.mysql.jdbc.Driver");
            conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
            String sql="Insert into transaksi values(?,?,?,?,?,?,?)";
            PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);
           
        
                st.setString(1, nama.getText());
                st.setObject(2, cbNamaKereta.getSelectedItem());
                st.setObject(3, cbKelas.getSelectedItem());
                st.setObject(4, cbJurusan.getSelectedItem());
                st.setString(5, txtHarga.getText());
                 st.setString(6, txtJumlah.getText());
                 st.setString(7, txtID.getText());
            int rs=st.executeUpdate();
            
            if(rs>0){
            JOptionPane.showMessageDialog(this,"Berhasil");
                tampilDataKeJTable();
            }
           
            txtID.setText(""); // txtNoAnggota Tidak Aktif
        nama.setText("");        // txtNama          Aktif
        cbNamaKereta.setSelectedItem("");
        cbKelas.setSelectedItem("");
        cbJurusan.setSelectedItem("");
        txtHarga.setText("");
        txtJumlah.setText("");
        
        
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Gagal Tuh.. Bego Lu " +e.getMessage());
        }
   
    
}//GEN-LAST:event_TambahActionPerformed

private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
// TODO add your handling code here:
    idoto();
}//GEN-LAST:event_bTambahActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    Master tampil = new Master();
                  tampil.setVisible(true);
                  dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
// TODO add your handling code here:
    txtID.setText(""); // txtNoAnggota Tidak Aktif
        nama.setText("");        // txtNama          Aktif
        cbNamaKereta.setSelectedItem("");
        cbKelas.setSelectedItem("");
        cbJurusan.setSelectedItem("");
        txtHarga.setText("");
        txtJumlah.setText("");
}//GEN-LAST:event_bBatalActionPerformed

private void txtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tambah;
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbJurusan;
    private javax.swing.JComboBox cbKelas;
    private javax.swing.JComboBox cbNamaKereta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtPrint;
    // End of variables declaration//GEN-END:variables
class JTextFieldFilter extends PlainDocument { 

    public static final String numeric = "0123456789"; 
    public static final String huruf = " abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ"; 
    public static final String alamat = " 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ.-()"; 
    protected String acceptedChars = null; 
    protected boolean negativeAccepted = false; 

    public JTextFieldFilter(String acceptedchars) { 
    acceptedChars = acceptedchars; 
    } 

    public void setNegativeAccepted(boolean negativeaccepted) { 
    if (acceptedChars.equals(numeric) || (acceptedChars.equals(huruf))){ 
    negativeAccepted = negativeaccepted; 
    acceptedChars += "-"; 
    } 

    } 

    public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException { 
    if (str == null) 
    return; 

    for (int i = 0; i < str.length(); i++) { 
    if (acceptedChars.indexOf(String.valueOf(str.charAt(i))) == -1) 
    return; 
    } 

    if (negativeAccepted && str.indexOf("-") != -1) { 
    if (str.indexOf("-") != 0 || offset != 0) { 
    return; 
    } 
    } 

    super.insertString(offset, str, attr); 
    } 
    }
    
    void cetuk(){
    JasperReport jasRep;
     JasperPrint jasPri;
     Map<String, Object> no = new HashMap<String, Object>();
     JasperDesign jasDes;
     
     try{
      Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
         
         File report = new File("Laporan/Lapor.jrxml");
         jasDes = JRXmlLoader.load(report);
         no.clear();
         HashMap hashMap = new HashMap();
         hashMap.put("Transaksi", txtID.getText());
         jasRep = JasperCompileManager.compileReport(jasDes);
         jasPri = JasperFillManager.fillReport(jasRep, hashMap, conn);
         JasperViewer.viewReport(jasPri, false);
         
     }catch (Exception e){
         JOptionPane.showMessageDialog(null, e.getMessage());
         
     } 
}
void cetuk1(){
    JasperReport jasRep;
     JasperPrint jasPri;
     Map<String, Object> no = new HashMap<String, Object>();
     JasperDesign jasDes;
     
     try{
      Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
         
         File report = new File("Laporan/Lapor.jrxml");
         jasDes = JRXmlLoader.load(report);
         no.clear();
         HashMap hashMap = new HashMap();
         hashMap.put("Transaksi", txtPrint.getText());
         jasRep = JasperCompileManager.compileReport(jasDes);
         jasPri = JasperFillManager.fillReport(jasRep, hashMap, conn);
         JasperViewer.viewReport(jasPri, false);
         
     }catch (Exception e){
         JOptionPane.showMessageDialog(null, e.getMessage());
         
     }
}

       public void idoto() {
        String sql;
     try{
        Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass); 
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        sql = "SELECT * FROM transaksi ORDER BY id DESC";
        PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;
            
            if (rs.next()) {
                String id = rs.getString("id").substring(1);
                String AN = "" + (Integer.parseInt(id) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "00";}
                else if(AN.length()==2)
                {Nol = "0";}
                else if(AN.length()==3)
                {Nol = "";}
                txtID.setText("A" + Nol + AN);//sesuaikan dengan variable namenya
            } else {
                txtID.setText("A001");//sesuaikan dengan variable namenya
            }
            rs.close();
        } catch (Exception e) {
        }
       }
       private void getData(){   // import java.sql.connection
  try{
         Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass); 
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        String sql="Select * from transaksi";
        PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String Kode_Tiket,Nama,Alamat,Kontak,Jenis,Harga,Jumlah;
        int no=0;
        while(rs.next()){
         no=no+1;
         Kode_Tiket=rs.getString("Nama_Pemesan");
         Nama=rs.getString("Nama_Kereta");
         Alamat=rs.getString("Kelas");
         Kontak=rs.getString("Jurusan");
         Jenis=rs.getString("Harga");
         Harga=rs.getString("Jumlah_Pemesanan");
         Jumlah=rs.getString("id");

         Object Data[]={no,Kode_Tiket,Nama,Alamat,Kontak,Jenis,Harga,Jumlah};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }// Akhir Method getData
    
    
    
private void setJTable(){
    String [] JudulKolom={"No","Nama_Pemesan","Nama_Kereta","Kelas","Jurusan","Harga","Jumlah_Pemesanan","id"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false};
                  
            @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    
    

    getData();
}// Akhir Method setJTable

    
  
public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("com.mysql.jdbc.Driver");
        conn  =(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);  
        String sql="Select * from transaksi";
        PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String Nama_Pemesan,Nama_Kereta,Kelas,Jurusan,Harga,Jumlah_Pemesan,id;
        int no=0;
        while(rs.next()){
         no=no+1;
         Nama_Pemesan=rs.getString("Nama_Pemesan");
         Nama_Kereta=rs.getString("Nama_Kereta");
         Kelas=rs.getString("Kelas");
         Jurusan=rs.getString("Jurusan");
         Harga=rs.getString("Harga");
         Jumlah_Pemesan=rs.getString("Jumlah_Pemesan");
         id=rs.getString("id");
         Object Data[]={no,Nama_Pemesan,Nama_Kereta,Kelas,Jurusan,Harga,Jumlah_Pemesan,id};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}
public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }


}